import type { Metadata } from 'next'

import Header from '@/components/Header'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'thops',
  description: 'Generated by create next app'
}

export default function Home () {
  const fetchData = async () => {
    try {
      const response = await fetch('/api/users', {
        headers: {
          accept: 'application/json',
          method: 'GET'
        }
      })
      if (response) {
        const data = await response.json()
        // setData(data)
        console.log(data)
      }
    } catch (error) {
      console.log(error)
    }
  }

  return (
    <main>
      <Header />
      <div>
        <Image src='/next.svg' alt='whops' width={200} height={1000} />
      </div>
    </main>
  )
}
